### ISSUE TITLE
How to use remote handler when i need to encode parameters in url?

### ISSUE THREAD

**Issue by Bidaya0** [dashborg/hibiki#9]
like this:
```
/api/v1/user/<int:id>
```
How do I add parameters correctly, there is no such example in the playground.

**Comment by sawka** [comment]
Hi, you can make a call to a dynamic URL by using the "callhandler" statement:
`$.result = callhandler(@url="/api/v1/user/" + $.id, @method="GET")`
The method will default to "GET" so it can be omitted.  All the non-@ params will be converted to URL parameters on the actual call.

There is some additional documentation here: https://docs.hibikihtml.com/reference/http-module/

**Comment by Bidaya0** [comment]
> Hi, you can make a call to a dynamic URL by using the "callhandler" statement: `$.result = callhandler(@url="/api/v1/user/" + $.id, @method="GET")` The method will default to "GET" so it can be omitted. All the non-@ params will be converted to URL parameters on the actual call.
> 
> There is some additional documentation here: https://docs.hibikihtml.com/reference/http-module/

Thank you for quick reply.
